#!/usr/bin/env python3
"""
Obesity Competitive Landscape Analysis

Generated by: competitive-specialist agent
Purpose: Analyze competitive dynamics in obesity therapeutic space
"""
import sys
from pathlib import Path

# Add scripts directory to path
script_dir = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(script_dir))

from competitive.queries import (
    get_trial_count,
    get_phase_distribution,
    get_sponsor_breakdown,
    get_intervention_analysis,
    get_status_breakdown
)
from competitive.functions import (
    calculate_competitive_intensity,
    assess_competitive_intensity_level,
    assess_market_maturity,
    assess_current_competition,
    assess_industry_activity,
    assess_moa_dominance,
    score_threat_level,
    calculate_phase_ratio,
    assess_pipeline_maturity
)


def main():
    print('=' * 100)
    print('OBESITY COMPETITIVE LANDSCAPE ANALYSIS')
    print('=' * 100)

    # Phase 1: Market Overview
    print('\n[1/5] Gathering market overview...')
    total_trials = get_trial_count('obesity', location='United States')
    status_breakdown = get_status_breakdown('obesity')

    recruiting_count = status_breakdown.get('recruiting', 0)
    active_count = status_breakdown.get('active_not_recruiting', 0)
    completed_count = status_breakdown.get('completed', 0)

    # Phase 2: Pipeline Analysis
    print('[2/5] Analyzing pipeline by phase...')
    all_phases = get_phase_distribution('obesity')
    active_phases = get_phase_distribution('obesity', status='recruiting OR active_not_recruiting')

    phase3_all = all_phases.get('PHASE3', 0)
    phase2_all = all_phases.get('PHASE2', 0)
    phase3_active = active_phases.get('PHASE3', 0)
    phase2_active = active_phases.get('PHASE2', 0)

    # Phase 3: Sponsor Analysis
    print('[3/5] Analyzing sponsor dynamics...')
    active_sponsors = get_sponsor_breakdown('obesity', status='recruiting OR active_not_recruiting')
    industry_count = active_sponsors.get('industry', 0)
    academic_count = active_sponsors.get('academic', 0)
    total_active = industry_count + academic_count

    # Phase 4: MOA/Drug Class Analysis
    print('[4/5] Analyzing mechanism of action landscape...')
    key_moas = ['GLP-1', 'GLP-1/GIP', 'semaglutide', 'tirzepatide', 'liraglutide']
    active_moas = get_intervention_analysis('obesity', key_moas, status='recruiting OR active_not_recruiting')
    all_moas = get_intervention_analysis('obesity', key_moas)

    glp1_active = active_moas.get('GLP-1', 0)
    glp1_all = all_moas.get('GLP-1', 0)

    # Phase 5: Competitive Metrics Calculation
    print('[5/5] Calculating competitive metrics...')

    # Competitive intensity
    intensity_score = calculate_competitive_intensity(recruiting_count, phase3_active, glp1_active)
    intensity_level = assess_competitive_intensity_level(intensity_score)

    # Market maturity
    maturity = assess_market_maturity(phase3_all)

    # Current competition
    competition = assess_current_competition(recruiting_count)

    # Industry activity
    industry_pct = (industry_count / total_active * 100) if total_active > 0 else 0
    industry_activity = assess_industry_activity(industry_pct)

    # MOA dominance
    glp1_pct = (glp1_active / total_active * 100) if total_active > 0 else 0
    glp1_dominance = assess_moa_dominance(glp1_pct)

    # Pipeline maturity
    phase32_ratio = calculate_phase_ratio(phase3_active, phase2_active)
    pipeline_maturity = assess_pipeline_maturity(phase32_ratio)

    # Generate Report
    print('\n' + '=' * 100)
    print('COMPETITIVE ANALYSIS RESULTS')
    print('=' * 100)

    print(f'\n## Executive Summary\n')
    print(f'**Market Maturity**: {maturity} ({phase3_all} Phase 3 trials total)')
    print(f'**Current Competition**: {competition} ({recruiting_count} recruiting trials)')
    print(f'**Competitive Intensity**: {intensity_level} (Score: {intensity_score:.0f}/1000)')
    print(f'**GLP-1 Dominance**: {glp1_dominance} ({glp1_pct:.1f}% of active trials)')

    print(f'\n## 1. Market Overview\n')
    print(f'Total Obesity Trials (US):       {total_trials:,}')
    print(f'  - Recruiting:                   {recruiting_count:,} ({recruiting_count/total_trials*100:.1f}%)')
    print(f'  - Active (not recruiting):      {active_count:,} ({active_count/total_trials*100:.1f}%)')
    print(f'  - Completed:                    {completed_count:,} ({completed_count/total_trials*100:.1f}%)')
    print(f'  - Total Active:                 {recruiting_count + active_count:,}')

    print(f'\n## 2. Pipeline Dynamics\n')
    print(f'### All Trials by Phase:')
    for phase, count in sorted(all_phases.items(), key=lambda x: x[1], reverse=True):
        pct = (count / total_trials * 100) if total_trials > 0 else 0
        phase_name = phase.replace('_', ' ').title()
        print(f'  {phase_name:20s}: {count:4d} trials ({pct:5.1f}%)')

    print(f'\n### Active Trials by Phase (Recruiting + Active):')
    for phase, count in sorted(active_phases.items(), key=lambda x: x[1], reverse=True):
        pct = (count / total_active * 100) if total_active > 0 else 0
        phase_name = phase.replace('_', ' ').title()
        print(f'  {phase_name:20s}: {count:4d} active ({pct:5.1f}%)')

    print(f'\n### Pipeline Maturity:')
    print(f'  Phase 3/2 Ratio:                {phase32_ratio:.2f} ({pipeline_maturity} pipeline)')
    print(f'  Phase 3 Active:                 {phase3_active} trials')
    print(f'  Phase 2 Active:                 {phase2_active} trials')

    print(f'\n## 3. Sponsor Dynamics (Active Trials)\n')
    print(f'Industry-sponsored:               {industry_count:,} trials ({industry_pct:.1f}%)')
    print(f'Academic/Other:                   {academic_count:,} trials ({(academic_count/total_active*100) if total_active > 0 else 0:.1f}%)')
    print(f'\nIndustry Activity Level:          {industry_activity}')
    print(f'Commercial Confidence:            {"Strong" if industry_pct > 50 else "Moderate" if industry_pct > 30 else "Limited"}')

    print(f'\n## 4. Mechanism of Action Landscape\n')
    print(f'### Active Trials by MOA/Drug:')
    sorted_moas = sorted(active_moas.items(), key=lambda x: x[1], reverse=True)
    for name, count in sorted_moas:
        pct = (count / total_active * 100) if total_active > 0 else 0
        all_count = all_moas.get(name, 0)
        print(f'  {name:20s}: {count:4d} active ({pct:4.1f}%), {all_count:4d} total')

    print(f'\n### GLP-1 Competitive Analysis:')
    print(f'  GLP-1 Class Dominance:          {glp1_dominance}')
    print(f'  Active GLP-1 Trials:            {glp1_active} ({glp1_pct:.1f}% of active trials)')
    print(f'  Total GLP-1 Trials:             {glp1_all} ({glp1_all/total_trials*100:.1f}% of all trials)')
    print(f'  Market Assessment:              {"Saturated - high differentiation required" if glp1_active > 50 else "Competitive - clear positioning needed" if glp1_active > 30 else "Emerging - room for entry"}')

    print(f'\n## 5. Competitive Intensity Analysis\n')
    print(f'Competitive Intensity Score:      {intensity_score:.0f}/1000')
    print(f'Assessment:                       {intensity_level}')
    print(f'\nScore Components:')
    print(f'  - Recruiting trials:            {recruiting_count} (patient enrollment competition)')
    print(f'  - Phase 3 programs:             {phase3_active} (near-term market entries 1-3 years)')
    print(f'  - Leading MOA (GLP-1):          {glp1_active} (mechanism saturation)')

    if intensity_score >= 700:
        assessment = "SATURATED MARKET - Very high barriers to differentiation. New entrants need breakthrough innovation or novel patient populations."
    elif intensity_score >= 500:
        assessment = "HIGHLY COMPETITIVE - Strong differentiation required. Focus on unmet needs and white space opportunities."
    elif intensity_score >= 300:
        assessment = "COMPETITIVE - Clear positioning needed. Opportunity for well-differentiated programs."
    else:
        assessment = "MODERATE COMPETITION - Room for new entrants with solid value proposition."

    print(f'\n**Market Assessment**: {assessment}')

    print(f'\n## 6. Threat Level Assessment\n')

    # Phase 3 threats (high threat)
    print(f'\n### 🔴 HIGH THREATS - Phase 3 Programs ({phase3_active} programs)')
    print(f'Launch Timeline:                  2-3 years (2026-2028)')
    print(f'Threat Level:                     HIGH (regulatory de-risked)')
    print(f'Key Risk:                         {phase3_active} programs will report data in next 1-3 years')
    print(f'Action Required:                  Monitor closely, prepare competitive response')

    # Phase 2 threats (moderate threat)
    print(f'\n### 🟡 MODERATE THREATS - Phase 2 Programs ({phase2_active} programs)')
    print(f'Launch Timeline:                  4-6 years (2029-2031)')
    print(f'Threat Level:                     MODERATE (execution risk)')
    print(f'Key Risk:                         Pipeline programs advancing to Phase 3')
    print(f'Action Required:                  Track progression, assess differentiation')

    # GLP-1 saturation (market threat)
    print(f'\n### ⚠️ MARKET SATURATION THREAT - GLP-1 Mechanism')
    print(f'Active GLP-1 Trials:              {glp1_active} ({glp1_dominance} dominance)')
    print(f'Saturation Level:                 {"VERY HIGH" if glp1_active > 50 else "HIGH" if glp1_active > 30 else "MODERATE"}')
    print(f'Implication:                      {"Severe" if glp1_active > 50 else "Significant"} mechanism crowding')
    print(f'Strategy:                         {"Alternative MOAs critical" if glp1_active > 50 else "Strong differentiation required"}')

    print(f'\n## 7. Strategic Implications\n')

    print(f'\n### Defensive Strategies (for market leaders):')
    print(f'1. Address {phase3_active} Phase 3 competitive threats before launch (2026-2028)')
    print(f'2. Differentiate on convenience, safety, or indication breadth')
    print(f'3. Build prescribing inertia and payer relationships')
    print(f'4. Consider indication expansion or combination therapy')

    print(f'\n### Offensive Strategies (for new entrants):')
    print(f'1. Avoid head-to-head GLP-1 competition ({glp1_active} active programs)')
    print(f'2. Target white space: alternative mechanisms, underserved populations')
    print(f'3. Focus on differentiation: oral, once-weekly, no fasting, broader indications')
    print(f'4. Consider precision medicine approaches (genetic patient selection)')

    print(f'\n### Market Entry Considerations:')
    competitive_barriers = []
    if intensity_score >= 700:
        competitive_barriers.append('VERY HIGH patient enrollment competition')
    if phase3_active > 40:
        competitive_barriers.append(f'{phase3_active} near-term competitive launches')
    if glp1_active > 50:
        competitive_barriers.append('GLP-1 mechanism saturation')
    if industry_pct > 60:
        competitive_barriers.append('Strong commercial player presence')

    if competitive_barriers:
        print(f'**Barriers to Entry:**')
        for barrier in competitive_barriers:
            print(f'  - {barrier}')
        print(f'\n**Recommendation**: {"Avoid unless breakthrough differentiation" if len(competitive_barriers) >= 3 else "Proceed with strong differentiation strategy"}')
    else:
        print(f'**Barriers to Entry**: Moderate')
        print(f'**Recommendation**: Opportunity for well-positioned programs')

    print('\n' + '=' * 100)
    print('ANALYSIS COMPLETE')
    print('=' * 100)


if __name__ == '__main__':
    main()
